import { Event, Sport } from './types';

export const MOCK_SPORTS: Sport[] = [
  { id: '1', name: 'All', slug: 'all' },
  { id: '2', name: 'Cricket', slug: 'cricket' },
  { id: '3', name: 'Badminton', slug: 'badminton' },
  { id: '4', name: 'Wrestling', slug: 'wrestling' },
  { id: '5', name: 'Shooting', slug: 'shooting' },
  { id: '6', name: 'Athletics', slug: 'athletics' },
  { id: '7', name: 'Hockey', slug: 'hockey' },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    name: 'India vs Australia Test Series',
    sport: 'Cricket',
    sportSlug: 'cricket',
    startDate: '2025-11-22',
    endDate: '2025-12-25',
    city: 'Perth',
    country: 'Australia',
    level: 'International',
    eventType: 'Test Match',
    indianParticipation: true,
    indianParticipants: ['Team India Men'],
    qualificationEvent: false,
    status: 'Upcoming',
    eventUrl: 'https://www.bcci.tv',
  },
  {
    id: 'e2',
    name: 'All England Open Badminton Championships',
    sport: 'Badminton',
    sportSlug: 'badminton',
    startDate: '2025-03-11',
    endDate: '2025-03-16',
    city: 'Birmingham',
    country: 'United Kingdom',
    level: 'International',
    eventType: 'Super 1000',
    indianParticipation: true,
    indianParticipants: ['PV Sindhu', 'Lakshya Sen', 'HS Prannoy'],
    qualificationEvent: true,
    status: 'Upcoming',
    eventUrl: 'https://www.allenglandbadminton.com',
  },
  {
    id: 'e3',
    name: 'Asian Wrestling Championships',
    sport: 'Wrestling',
    sportSlug: 'wrestling',
    startDate: '2025-04-15',
    endDate: '2025-04-20',
    city: 'New Delhi',
    country: 'India',
    level: 'International',
    eventType: 'Championship',
    indianParticipation: true,
    indianParticipants: ['Aman Sehrawat', 'Antim Panghal', 'Vinesh Phogat'],
    qualificationEvent: true,
    status: 'Upcoming',
    eventUrl: 'https://uww.org',
  },
  {
    id: 'e4',
    name: 'National Shooting Selection Trials',
    sport: 'Shooting',
    sportSlug: 'shooting',
    startDate: '2025-02-10',
    endDate: '2025-02-18',
    city: 'Bhopal',
    country: 'India',
    level: 'National',
    eventType: 'Trials',
    indianParticipation: true,
    indianParticipants: ['Manu Bhaker', 'Esha Singh', 'Arjun Babuta'],
    qualificationEvent: true,
    status: 'Upcoming',
    eventUrl: 'https://www.thenrai.in',
  },
  {
    id: 'e5',
    name: 'World Athletics Championships',
    sport: 'Athletics',
    sportSlug: 'athletics',
    startDate: '2025-09-13',
    endDate: '2025-09-21',
    city: 'Tokyo',
    country: 'Japan',
    level: 'International',
    eventType: 'World Championship',
    indianParticipation: true,
    indianParticipants: ['Neeraj Chopra', 'Kishore Jena', 'Priyanka Goswami'],
    qualificationEvent: false,
    status: 'Upcoming',
    eventUrl: 'https://worldathletics.org',
  }
];